import React, { ReactNode } from "react";
import Footer from "../footer/Footer";
import Navbar from "../header/Navbar";
import Head from "next/head";

interface MainLayoutProps {
  children: ReactNode;
}

const MainLayout = ({ children }: MainLayoutProps) => {
  return (
    <>
      <Head>
        <title>Hotdog shops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Hotdog shop locator New York</h1>
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default MainLayout;
